# -*- coding: utf-8 -*-
"""sentiment analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KGZ157dvCfQfv9uaIiBU4GMeDKagUppJ
"""

!pip install newspaper3k lxml[html_clean]
import nltk
nltk.download('punkt_tab')
from textblob import TextBlob
from newspaper import Article
url = "https://edition.cnn.com/2021/08/30/india/dalit-rape-men-charged-india-intl-hnk/index.html"
article = Article(url)
article.download()
article.parse()
article.nlp()
text = article.summary
print(text)
blob = TextBlob(text)
sentiment = blob.sentiment.polarity # -1 to 1
print(sentiment)